id: I895AD120
legacy_id: P000381
ocr_import_info:
  bdrc_scan_id: W1KG5377
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T13:04:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:16:52.861373+00:00'
last_modified: 2022-09-01 01:17:13.666522
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5377
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5377
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད།
  author: ཁྱུང་ཕྲུག་བྱམས་པ་བཀྲ་ཤིས།
statistics:
  ocr_word_mean_confidence_index: 0.9787508255823789
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG5394:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5394
      total_pages: 450
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG5394.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9765946027394887
    legacy_id: v002
  I1KG5393:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5393
      total_pages: 618
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5393.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9787587490931435
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
