id: P000381
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:02.337905
source_metadata:
  id: bdr:W1KG5377
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད་
  author: ''
  volumes:
    181e3480151c42808d0a31cead119f7b:
      image_group_id: I1KG5393
      title: Volume 1 of phar phyin mtha' dpyod
      volume_number: 1
      total_pages: 618
      base_file: v001.txt
    94909b7f8f384f18801cfe3e6ecb0aa4:
      image_group_id: I1KG5394
      title: Volume 2 of phar phyin mtha' dpyod
      volume_number: 2
      total_pages: 450
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
